We should use labels:  
1.cars_train_annos (train set)  
2.cars_test_annos_withlabels (test sett)  
3.cars_meta (classes mapping)

In [32]:
import scipy.io
import os
import numpy as np

In [33]:
car_annos = "dataset/cars_annos.mat"
cars_test_annos_withlabels = "dataset/cars_test_annos_withlabels.mat"
bmw10_annos = "dataset/bmw10_release/bmw10_annos.mat"
cars_meta = "dataset/car_devkit/devkit/cars_meta.mat"
cars_test_annos = "dataset/car_devkit/devkit/cars_test_annos.mat"
cars_train_annos = "dataset/car_devkit/devkit/cars_train_annos.mat"

assert os.path.isfile(car_annos)
assert os.path.isfile(cars_test_annos_withlabels)
assert os.path.isfile(bmw10_annos)
assert os.path.isfile(cars_meta)
assert os.path.isfile(cars_test_annos)
assert os.path.isfile(cars_train_annos)

In [74]:
# car_annos
mat = scipy.io.loadmat(car_annos)
"""
dataset:
dataset/car_ims
keys:
1.annotations
2.class_names
annotations index:
1.filename
2.box_x1
3.box_y1
4.box_x2
5.box_y2
6.class
7.train/test set
"""
print(mat.keys())
print(mat["annotations"].ravel().shape)
print(mat["annotations"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'annotations', 'class_names'])
(16185,)
(array(['car_ims/000001.jpg'], dtype='<U18'), array([[112]], dtype=uint8), array([[7]], dtype=uint8), array([[853]], dtype=uint16), array([[717]], dtype=uint16), array([[1]], dtype=uint8), array([[0]], dtype=uint8))


In [70]:
# cars_test_annos_withlabels
mat = scipy.io.loadmat(cars_test_annos_withlabels)
"""
dataset:
dataset/car_test
keys:
1.annotations
annotations index:
1.box_x1
2.box_y1
3.box_x2
4.box_y2
5.class
6.filename
"""
print(mat.keys())
print(mat["annotations"].ravel().shape)
print(mat["annotations"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'annotations'])
(8041,)
(array([[30]], dtype=uint8), array([[52]], dtype=uint8), array([[246]], dtype=uint8), array([[147]], dtype=uint8), array([[181]], dtype=uint8), array(['00001.jpg'], dtype='<U9'))


In [69]:
# bmw10_annos
mat = scipy.io.loadmat(bmw10_annos)
"""
keys:
1.train_indices
2.test_indices
3.annos
annotations index:
1.filename
2.class???
3.box_x1
4.box_x2
5.box_y1
6.box_y2
7.size_y
8.size_x
"""
print(mat.keys())
print(mat["annos"].ravel().shape)
print(mat["annos"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'train_indices', 'test_indices', 'annos'])
(512,)
(array(['10/150302307.thumb.jpg'], dtype='<U22'), array([[9]], dtype=uint8), array([[42]], dtype=int32), array([[217]], dtype=int32), array([[32]], dtype=int32), array([[163]], dtype=int32), array([[183]], dtype=uint8), array([[275]], dtype=uint16))


In [75]:
# cars_meta
mat = scipy.io.loadmat(cars_meta)
"""
keys:
1.class_names
class_names index:
1.class_names
"""
print(mat.keys())
print(mat["class_names"].ravel().shape)
print(mat["class_names"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'class_names'])
(196,)
['AM General Hummer SUV 2000']


In [66]:
# cars_test_annos
mat = scipy.io.loadmat(cars_test_annos)
"""
dataset:
dataset/car_test
keys:
1.annotations
annotations index:
1.box_x1
2.box_y1
3.box_x2
4.box_y2
5.filename
"""
print(mat.keys())
print(mat["annotations"].ravel().shape)
print(mat["annotations"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'annotations'])
(8041,)
(array([[30]], dtype=uint8), array([[52]], dtype=uint8), array([[246]], dtype=uint8), array([[147]], dtype=uint8), array(['00001.jpg'], dtype='<U9'))


In [65]:
# cars_train_annos
mat = scipy.io.loadmat(cars_train_annos)
"""
dataset:
dataset/car_train
keys:
1.annotations
annotations index:
1.box_x1
2.box_y1
3.box_x2
4.box_y2
5.class
6.filename
"""
print(mat.keys())
print(mat["annotations"].ravel().shape)
print(mat["annotations"].ravel()[0])

dict_keys(['__header__', '__version__', '__globals__', 'annotations'])
(8144,)
(array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'], dtype='<U9'))
